# This is the revised GitHub Actions workflow for a self-hosted runner.
# It runs directly on the Raspberry Pi.

name: Deploy to Raspberry Pi (Self-Hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # This is the key change: it tells GitHub to send this job
    # to any of our runners that are labeled "self-hosted".
    runs-on: self-hosted

    steps:
      # 1. Checks-out your repository under the runner's workspace.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. These commands are now run directly on the Pi by the runner.
      #    We no longer need complex SSH actions.
      - name: Deploy files and restart services
        run: |
          echo "Starting local deployment on Pi..."
          # The source is the current directory where the code was checked out.
          # The target is our application directory.
          # Using rsync is still the best way to move the files efficiently.
          rsync -rltgoDzvO --delete ./ /home/john/the_shepherd/shepherd/
          
          echo "Restarting Shepherd services..."
          sudo systemctl restart shepherd-app.service
          sudo systemctl restart shepherd-ingestor.service
          sudo systemctl restart shepherd-summarizer.service
          sudo systemctl restart shepherd-pricer.service
          echo "Deployment complete."