# This is a GitHub Actions workflow.
# It will automatically deploy the code to your Raspberry Pi
# every time you push a change to the 'main' branch.

name: Deploy to Raspberry Pi

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Syncs the files from the repo to your Pi using rsync over SSH
      - name: Deploy files to Pi
        uses: easingthemes/ssh-deploy@v4.1.10 # Using a well-maintained action
        with:
          # The private SSH key we stored in GitHub secrets
          SSH_PRIVATE_KEY: ${{ secrets.PI_SSH_KEY }}
          # The IP address of the Pi
          REMOTE_HOST: ${{ secrets.PI_HOST_ZERO }}
          # The username on the Pi
          REMOTE_USER: ${{ secrets.PI_USER }}
          # The source directory from the repo to copy
          SOURCE: "./"
          # The target directory on the Pi
          TARGET: "/home/john/the_shepherd/shepherd"
          # Using rsync arguments to make it efficient and clean
          ARGS: "-rltgoDzvO --delete"

      # 3. Executes commands on the Pi to restart the services
      - name: Restart services on Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            echo "Restarting Shepherd services..."
            sudo systemctl restart shepherd-app.service
            sudo systemctl restart shepherd-ingestor.service
            echo "Services restarted successfully."